<a href="https://colab.research.google.com/github/asrorbek0202/ML_machineLearning/blob/main/pandas_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Pandas ==> jadvallar bilan ishlash, DataFrame va Series, fayl o'qish, filtrlash, guruhlash, birlashtrish va tezkor malumot tahlili

# Series ==> 1D(1 ta ustun)
import pandas as pd
import numpy as np

costs = pd.Series([620, 780, 1150, 380], name="narx")
print(costs)

0     620
1     780
2    1150
3     380
Name: narx, dtype: int64

In [4]:
# DataFrame ==> butun jadval
homes = pd.DataFrame({
    "area":  [65, 90, 120, 45, 78],
    "rooms": [2, 3, 4, 1, 3],
    "location":   ["Yunusobod", "Chilonzor", "Mirzo Ulug'bek", "Sergeli", "Yakkasaroy"],
    "age":    [12, 5, 2, 25, 8],
    "cost":    [620, 780, 1150, 380, 810],
})

print(homes)

   area  rooms        location  age  cost
0    65      2       Yunusobod   12   620
1    90      3       Chilonzor    5   780
2   120      4  Mirzo Ulug'bek    2  1150
3    45      1         Sergeli   25   380
4    78      3      Yakkasaroy    8   810

In [14]:
print(homes.head(3))       # birinchi 3 qator
print(homes.tail(3))       # oxirgi 3 qator
print(homes.shape)         # (qatorlar, ustunlar)
print(homes.columns)       # ustun nomlari
print(homes.dtypes)
homes.info()

   area  rooms        location  age  cost
0    65      2       Yunusobod   12   620
1    90      3       Chilonzor    5   780
2   120      4  Mirzo Ulug'bek    2  1150
   area  rooms        location  age  cost
2   120      4  Mirzo Ulug'bek    2  1150
3    45      1         Sergeli   25   380
4    78      3      Yakkasaroy    8   810
(5, 5)
Index(['area', 'rooms', 'location', 'age', 'cost'], dtype='object')
area         int64
rooms        int64
location    object
age          int64
cost         int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      5 non-null      int64
 1   rooms     5 non-null      int64
 2   location  5 non-null      object
 3   age       5 non-null      int64
 4   cost      5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [6]:
print(homes.describe())

             area     rooms        age         cost
count    5.000000  5.000000   5.000000     5.000000
mean    79.600000  2.600000  10.400000   748.000000
std     28.076681  1.140175   8.961027   282.081548
min     45.000000  1.000000   2.000000   380.000000
25%     65.000000  2.000000   5.000000   620.000000
50%     78.000000  3.000000   8.000000   780.000000
75%     90.000000  3.000000  12.000000   810.000000
max    120.000000  4.000000  25.000000  1150.000000

In [7]:
homes["cost"]        # Series - bir o'lchovli
homes[["cost"]]      # DataFrame - ikki o'lchovli

   cost
0   620
1   780
2  1150
3   380
4   810

In [8]:
print(homes.iloc[0])          # pozitsiya bo'yicha
print(homes.iloc[1:3])        # 1 va 2-qator
print(homes.iloc[0, 2])       # birinchi qator, uchinchi ustun

print(homes.loc[0])           # indeks bo'yicha
print(homes.loc[0, "cost"])   # indeks va ustun nomi
print(homes.loc[0:2, ["area", "cost"]])

area               65
rooms               2
location    Yunusobod
age                12
cost              620
Name: 0, dtype: object
   area  rooms        location  age  cost
1    90      3       Chilonzor    5   780
2   120      4  Mirzo Ulug'bek    2  1150
Yunusobod
area               65
rooms               2
location    Yunusobod
age                12
cost              620
Name: 0, dtype: object
620
   area  cost
0    65   620
1    90   780
2   120  1150

In [9]:
expensive = homes[homes["cost"] > 700]
print(expensive)

   area  rooms        location  age  cost
1    90      3       Chilonzor    5   780
2   120      4  Mirzo Ulug'bek    2  1150
4    78      3      Yakkasaroy    8   810

In [10]:
# Guruhlash
trade = pd.DataFrame({
    "location":  ["Chilonzor", "Chilonzor", "Sergeli", "Sergeli", "Yunusobod"],
    "rooms": [2, 3, 2, 1, 3],
    "cost":   [700, 780, 450, 380, 900],
})

print(trade.groupby("location")["cost"].mean())

location
Chilonzor    740.0
Sergeli      415.0
Yunusobod    900.0
Name: cost, dtype: float64

In [16]:
missed_info = {
    "location": ["Chilonzor", None, "Sergeli", None, "Yunusobod","Olmaliq"],
     "rooms": [2, None, 2, 1, None,3],
}
missing_inf = pd.DataFrame(missed_info)
print(missing_inf)

    location  rooms
0  Chilonzor    2.0
1       None    NaN
2    Sergeli    2.0
3       None    1.0
4  Yunusobod    NaN
5    Olmaliq    3.0

In [19]:
missing_inf.isnull()

   location  rooms
0     False  False
1      True   True
2     False  False
3      True  False
4     False   True
5     False  False

In [20]:
missing_inf.isnull().sum()

location    2
rooms       2
dtype: int64

In [21]:
missing_inf.dropna()

    location  rooms
0  Chilonzor    2.0
2    Sergeli    2.0
5    Olmaliq    3.0

In [23]:
missing_inf.dropna(how="all")

    location  rooms
0  Chilonzor    2.0
2    Sergeli    2.0
3       None    1.0
4  Yunusobod    NaN
5    Olmaliq    3.0

In [24]:
missing_inf.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [26]:
missing_inf.dropna(subset=["rooms"])

    location  rooms
0  Chilonzor    2.0
2    Sergeli    2.0
3       None    1.0
5    Olmaliq    3.0

In [27]:
missing_inf.fillna(0)

    location  rooms
0  Chilonzor    2.0
1          0    0.0
2    Sergeli    2.0
3          0    1.0
4  Yunusobod    0.0
5    Olmaliq    3.0

In [4]:
import pandas as pd
data = pd.read_csv("Health_AnimalBites.csv")
data.head()

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
1,1986-02-12 00:00:00,DOG,NaN,UNKNOWN,BRO & BLA,NaN,NaN,40218,NO,BODY,1986-02-12 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
2,1987-05-07 00:00:00,DOG,NaN,UNKNOWN,NaN,NaN,NaN,40219,NO,BODY,1990-05-07 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
3,1988-10-02 00:00:00,DOG,NaN,MALE,BLA & BRO,NaN,NaN,NaN,NO,BODY,1990-10-02 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN
4,1989-08-29 00:00:00,DOG,NaN,FEMALE,BLK-WHT,NaN,NaN,NaN,NO,BODY,NaN,UNKNOWN,NaN,NaN,UNKNOWN

In [5]:
data.tail()

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
8998,2017-09-05 00:00:00,DOG,NaN,NaN,NaN,NaN,NaN,40243,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
8999,2017-09-07 00:00:00,DOG,POMERANIAN,MALE,RED,NaN,NaN,40204,NaN,HEAD,NaN,NaN,NaN,NaN,NaN
9000,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,MALE,BROWN,NaN,NaN,47130,NaN,UNKNOWN,NaN,NaN,NaN,NaN,NaN
9001,2017-09-07 00:00:00,DOG,LABRADOR RETRIV,FEMALE,BLK WHT,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN
9002,2017-09-07 00:00:00,DOG,BOXER,NaN,BRN BLK,NaN,NaN,40229,NaN,BODY,NaN,NaN,NaN,NaN,NaN

In [6]:
# qirqib olib saqlash va saqlangan malumotni chaqirib yana ishlash mumkin
data.to_excel("new_info.xlsx")